import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {GlobalProvider} from '@/components/GlobalStore';
import {Toaster} from "@/components/ui/toaster";
import * as React from "react";
import {Footer} from "@/components/footer";
import {ButtonRow} from "@/components/buttonLink";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Translator4mds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className+" relative"}>
      <GlobalProvider>
        {children}

      </GlobalProvider>
      <Toaster/>
      <ButtonRow />
      <Footer />
    </body>
    </html>
  );
}
